
package controle_de_acesso;

import br.com.jmary.home.Home;
import br.com.jmary.home.imagens.Imagens_Internas;
import br.com.jmary.home.jpa.DAOGenericoJPA;
import br.com.jmary.home.jpa.JPAUtil;
import br.com.jmary.utilidades.Exportando;
import javax.swing.ImageIcon;
import br.com.jmary.utilidades.JOPM;
import br.com.jmary.utilidades.PopupMenu_Colar;
import controle_de_acesso_beans.ControleDeAcesso;
import home_controle_menus_norte.imagens.Imagens_Menu_Norte;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import java.io.ByteArrayOutputStream;
import login_do_sistema.Login;
import usuarios_do_sistema_beans.UsuarioSistema;

/**
 *
 * @author AnaMariana
 */
public class Controle_De_Acesso_02_Cadastrar_Visualizar extends javax.swing.JPanel {
    
    Home Home;
    String status_cadastro;
    ControleDeAcesso ControleDeAcesso_Recebido;
    UsuarioSistema UsuarioSistema_Recebido;
    JTabbedPane JTabbedPane_Recebido;
    PopupMenu_Colar PopupMenu_Colar;

    /** Creates new form SombraVendas
     * @param Home2
     * @param JTabbedPane_Recebido2
     * @param status_cadastro2 */
    public Controle_De_Acesso_02_Cadastrar_Visualizar( Home Home2, JTabbedPane JTabbedPane_Recebido2, String status_cadastro2 ) {
        initComponents();
        
        Home = Home2;  
        status_cadastro = status_cadastro2;
        JTabbedPane_Recebido = JTabbedPane_Recebido2;
        setar_Dados_Iniciais();
        
    }
    
    public Controle_De_Acesso_02_Cadastrar_Visualizar( Home Home2, JTabbedPane JTabbedPane_Recebido2, String status_cadastro2, 
            ControleDeAcesso ControleDeAcesso_Recebido2, UsuarioSistema UsuarioSistema_Recebido2 ) {
        initComponents();
        
        Home = Home2;  
        status_cadastro = status_cadastro2;        
        JTabbedPane_Recebido = JTabbedPane_Recebido2;
        
        ControleDeAcesso_Recebido = ControleDeAcesso_Recebido2;
        UsuarioSistema_Recebido = UsuarioSistema_Recebido2;
                
        setar_Dados_Iniciais();
    }
    
    private void setar_Dados_Iniciais(){
        /*new Thread() {   @Override public void run() {*/ try {  
            
//////////////////////////////////////////////////////////////////////////////////////////////            
            imgURL  = Imagens_Menu_Norte.class.getResource("seta_para_baixo.png");
            icon    = new ImageIcon( imgURL );  
            
            imgURL2  = Imagens_Menu_Norte.class.getResource("seta_para_cima.png");
            icon2   = new ImageIcon( imgURL2 ); 
//////////////////////////////////////////////////////////////////////////////////////////////

            if(status_cadastro.equalsIgnoreCase("Cadastrando...")){
                
                btExcluir.setVisible(false);
                
                mostrar_Ocultar_Jp_Padrao_Tabela();
            }
            else if(status_cadastro.equalsIgnoreCase("Visualizando...")){
                
                btExcluir.setVisible(false);
                btSalvar.setVisible(false);
                
                setar_Visualizacao_Recebida();
                //setarImagem_Principal();
                
                desabilitar_componentes();
            }
            else if(status_cadastro.equalsIgnoreCase("Alterando...")){
                
                setar_Visualizacao_Recebida();                
            }
        } catch( Exception e ){  } //} }.start();
    }   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Pergunta = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jp_Padrao_Tabela = new javax.swing.JPanel();
        jpO = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        JPOpcao_14 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        JPOpcao_15 = new javax.swing.JPanel();
        lb_Cadastrado_Por = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        JPOpcao_13 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        JPOpcao_12 = new javax.swing.JPanel();
        lb_Alterado_Por = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        JPOpcao_18 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        JPOpcao_19 = new javax.swing.JPanel();
        lb_Data_Cadastro = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        JPOpcao_16 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        JPOpcao_17 = new javax.swing.JPanel();
        lb_Data_Ultima_Alteracao = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        JPOpcao_28 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        JPOpcao_29 = new javax.swing.JPanel();
        tf_USUARIO = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();
        JPOpcao_30 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        cb_TABELA = new javax.swing.JComboBox();
        jPanel32 = new javax.swing.JPanel();
        JPOpcao_34 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        rb_ACESSO_A_TABELA = new javax.swing.JRadioButton();
        rb_VISUALIZAR = new javax.swing.JRadioButton();
        rb_ALTERAR = new javax.swing.JRadioButton();
        rb_CONSULTAR = new javax.swing.JRadioButton();
        rb_EXCLUIR = new javax.swing.JRadioButton();
        rb_CONSULTA_SQL = new javax.swing.JRadioButton();
        rb_CADASTRAR = new javax.swing.JRadioButton();
        rb_CADASTRO_AUTO = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(811, 593));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1170, 1202));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Controle de Acesso - Cadastrar/Visualizar");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/seta_para_cima.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpOLayout = new javax.swing.GroupLayout(jpO);
        jpO.setLayout(jpOLayout);
        jpOLayout.setHorizontalGroup(
            jpOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpOLayout.setVerticalGroup(
            jpOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        JPOpcao_14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_14.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_14MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_14MousePressed(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel68.setText("Cadastrado Por.: ");

        javax.swing.GroupLayout JPOpcao_14Layout = new javax.swing.GroupLayout(JPOpcao_14);
        JPOpcao_14.setLayout(JPOpcao_14Layout);
        JPOpcao_14Layout.setHorizontalGroup(
            JPOpcao_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        JPOpcao_14Layout.setVerticalGroup(
            JPOpcao_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_15.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_15.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_15MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_15MousePressed(evt);
            }
        });

        lb_Cadastrado_Por.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_Cadastrado_Por.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout JPOpcao_15Layout = new javax.swing.GroupLayout(JPOpcao_15);
        JPOpcao_15.setLayout(JPOpcao_15Layout);
        JPOpcao_15Layout.setHorizontalGroup(
            JPOpcao_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Cadastrado_Por, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_15Layout.setVerticalGroup(
            JPOpcao_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_Cadastrado_Por, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPOpcao_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPOpcao_15, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPOpcao_15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPOpcao_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JPOpcao_13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_13.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_13MousePressed(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel60.setText("Alterado Por (Última Alteração).: ");

        javax.swing.GroupLayout JPOpcao_13Layout = new javax.swing.GroupLayout(JPOpcao_13);
        JPOpcao_13.setLayout(JPOpcao_13Layout);
        JPOpcao_13Layout.setHorizontalGroup(
            JPOpcao_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        JPOpcao_13Layout.setVerticalGroup(
            JPOpcao_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_12.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_12.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_12MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_12MousePressed(evt);
            }
        });

        lb_Alterado_Por.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_Alterado_Por.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout JPOpcao_12Layout = new javax.swing.GroupLayout(JPOpcao_12);
        JPOpcao_12.setLayout(JPOpcao_12Layout);
        JPOpcao_12Layout.setHorizontalGroup(
            JPOpcao_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Alterado_Por, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_12Layout.setVerticalGroup(
            JPOpcao_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_Alterado_Por, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPOpcao_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPOpcao_12, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPOpcao_12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPOpcao_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JPOpcao_18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_18.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_18MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_18MousePressed(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel72.setText("Data Cadastro.: ");

        javax.swing.GroupLayout JPOpcao_18Layout = new javax.swing.GroupLayout(JPOpcao_18);
        JPOpcao_18.setLayout(JPOpcao_18Layout);
        JPOpcao_18Layout.setHorizontalGroup(
            JPOpcao_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        JPOpcao_18Layout.setVerticalGroup(
            JPOpcao_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_19.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_19.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_19.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_19MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_19MousePressed(evt);
            }
        });

        lb_Data_Cadastro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_Data_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout JPOpcao_19Layout = new javax.swing.GroupLayout(JPOpcao_19);
        JPOpcao_19.setLayout(JPOpcao_19Layout);
        JPOpcao_19Layout.setHorizontalGroup(
            JPOpcao_19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Data_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_19Layout.setVerticalGroup(
            JPOpcao_19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_Data_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPOpcao_18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPOpcao_19, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPOpcao_19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPOpcao_18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JPOpcao_16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_16.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_16MousePressed(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel70.setText("Data última Alteração.: ");

        javax.swing.GroupLayout JPOpcao_16Layout = new javax.swing.GroupLayout(JPOpcao_16);
        JPOpcao_16.setLayout(JPOpcao_16Layout);
        JPOpcao_16Layout.setHorizontalGroup(
            JPOpcao_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        JPOpcao_16Layout.setVerticalGroup(
            JPOpcao_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_17.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_17.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_17.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_17MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_17MousePressed(evt);
            }
        });

        lb_Data_Ultima_Alteracao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_Data_Ultima_Alteracao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout JPOpcao_17Layout = new javax.swing.GroupLayout(JPOpcao_17);
        JPOpcao_17.setLayout(JPOpcao_17Layout);
        JPOpcao_17Layout.setHorizontalGroup(
            JPOpcao_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Data_Ultima_Alteracao, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_17Layout.setVerticalGroup(
            JPOpcao_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_Data_Ultima_Alteracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPOpcao_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPOpcao_17, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPOpcao_17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPOpcao_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jp_Padrao_TabelaLayout = new javax.swing.GroupLayout(jp_Padrao_Tabela);
        jp_Padrao_Tabela.setLayout(jp_Padrao_TabelaLayout);
        jp_Padrao_TabelaLayout.setHorizontalGroup(
            jp_Padrao_TabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_Padrao_TabelaLayout.createSequentialGroup()
                .addGroup(jp_Padrao_TabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_Padrao_TabelaLayout.setVerticalGroup(
            jp_Padrao_TabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_Padrao_TabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/livroTp.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setPreferredSize(new java.awt.Dimension(185, 31));
        btSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btSalvarMousePressed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/exluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setPreferredSize(new java.awt.Dimension(185, 31));
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExcluirMousePressed(evt);
            }
        });

        JPOpcao_28.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(153, 0, 153)));
        JPOpcao_28.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_28MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_28MousePressed(evt);
            }
        });

        jLabel81.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel81.setText("  Usuário:");

        jLabel83.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/usuarios.gif"))); // NOI18N
        jLabel83.setToolTipText("Selecionar Usuário");
        jLabel83.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel83MousePressed(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_28Layout = new javax.swing.GroupLayout(JPOpcao_28);
        JPOpcao_28.setLayout(JPOpcao_28Layout);
        JPOpcao_28Layout.setHorizontalGroup(
            JPOpcao_28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_28Layout.createSequentialGroup()
                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel83)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPOpcao_28Layout.setVerticalGroup(
            JPOpcao_28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JPOpcao_29.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_29.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_29.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_29MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_29MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_29MousePressed(evt);
            }
        });

        tf_USUARIO.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_USUARIO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_USUARIO.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_USUARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_USUARIOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_USUARIOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_USUARIOMouseExited(evt);
            }
        });
        tf_USUARIO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_USUARIOKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_29Layout = new javax.swing.GroupLayout(JPOpcao_29);
        JPOpcao_29.setLayout(JPOpcao_29Layout);
        JPOpcao_29Layout.setHorizontalGroup(
            JPOpcao_29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_USUARIO, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_29Layout.setVerticalGroup(
            JPOpcao_29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_29Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPOpcao_29, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(JPOpcao_28, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addComponent(JPOpcao_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(JPOpcao_29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JPOpcao_30.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(153, 0, 153)));
        JPOpcao_30.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_30MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_30MousePressed(evt);
            }
        });

        jLabel82.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel82.setText("  Tabela:");

        cb_TABELA.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cb_TABELA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USUARIO_SISTEMA", "USUARIO_IMAGENS", "ESTABELECIMENTO", "ESTABELECIMENTO_IMAGENS", "CONTROLE_DE_ACESSO" }));
        cb_TABELA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cb_TABELA.setPreferredSize(new java.awt.Dimension(212, 23));
        cb_TABELA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TABELAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_30Layout = new javax.swing.GroupLayout(JPOpcao_30);
        JPOpcao_30.setLayout(JPOpcao_30Layout);
        JPOpcao_30Layout.setHorizontalGroup(
            JPOpcao_30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_30Layout.createSequentialGroup()
                .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
            .addGroup(JPOpcao_30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_TABELA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPOpcao_30Layout.setVerticalGroup(
            JPOpcao_30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_30Layout.createSequentialGroup()
                .addComponent(jLabel82)
                .addGap(2, 2, 2)
                .addComponent(cb_TABELA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPOpcao_30, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addComponent(JPOpcao_30, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPOpcao_34.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(153, 0, 153)));
        JPOpcao_34.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_34MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_34MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_34MousePressed(evt);
            }
        });

        jLabel84.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel84.setText("  Controle:");

        rb_ACESSO_A_TABELA.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rb_ACESSO_A_TABELA.setText("ACESSO_A_TABELA");

        rb_VISUALIZAR.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rb_VISUALIZAR.setText("VISUALIZAR");

        rb_ALTERAR.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rb_ALTERAR.setText("ALTERAR");

        rb_CONSULTAR.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rb_CONSULTAR.setText("CONSULTAR");

        rb_EXCLUIR.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rb_EXCLUIR.setText("EXCLUIR");

        rb_CONSULTA_SQL.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rb_CONSULTA_SQL.setText("CONSULTA_SQL");

        rb_CADASTRAR.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rb_CADASTRAR.setText("CADASTRAR");

        rb_CADASTRO_AUTO.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rb_CADASTRO_AUTO.setText("CADASTRO_AUTO");

        javax.swing.GroupLayout JPOpcao_34Layout = new javax.swing.GroupLayout(JPOpcao_34);
        JPOpcao_34.setLayout(JPOpcao_34Layout);
        JPOpcao_34Layout.setHorizontalGroup(
            JPOpcao_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPOpcao_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPOpcao_34Layout.createSequentialGroup()
                        .addGroup(JPOpcao_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_ALTERAR, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_CONSULTAR)
                            .addComponent(rb_VISUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_ACESSO_A_TABELA))
                        .addGap(18, 18, 18)
                        .addGroup(JPOpcao_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_CADASTRO_AUTO, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(rb_CADASTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rb_CONSULTA_SQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rb_EXCLUIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(166, 166, 166))
        );
        JPOpcao_34Layout.setVerticalGroup(
            JPOpcao_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_34Layout.createSequentialGroup()
                .addComponent(jLabel84)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPOpcao_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPOpcao_34Layout.createSequentialGroup()
                        .addComponent(rb_ACESSO_A_TABELA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_VISUALIZAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_CONSULTAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_ALTERAR))
                    .addGroup(JPOpcao_34Layout.createSequentialGroup()
                        .addComponent(rb_EXCLUIR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_CONSULTA_SQL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_CADASTRAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_CADASTRO_AUTO)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPOpcao_34, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPOpcao_34, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Dados Básicos", jPanel1);

        javax.swing.GroupLayout PerguntaLayout = new javax.swing.GroupLayout(Pergunta);
        Pergunta.setLayout(PerguntaLayout);
        PerguntaLayout.setHorizontalGroup(
            PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_Padrao_Tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PerguntaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addComponent(jTabbedPane2))
                .addContainerGap())
        );
        PerguntaLayout.setVerticalGroup(
            PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerguntaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(PerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_Padrao_Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Cadastrar/Visualizar", Pergunta);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

   
    private URL       imgURL; 
    private ImageIcon icon;            
    private URL       imgURL2;
    private ImageIcon icon2;
    private boolean cimabaixo = true; 
    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        
        mostrar_Ocultar_Jp_Padrao_Tabela();
    }//GEN-LAST:event_jLabel3MousePressed

    private void mostrar_Ocultar_Jp_Padrao_Tabela() {                                     
        try{

            if( cimabaixo == false ){
                cimabaixo = true;
                
                jLabel3.setToolTipText( "Ocultar Submenu" );
                jLabel3.setIcon( icon2 );              
                
                jp_Padrao_Tabela.setVisible(true);
            } else if( cimabaixo == true ){
                cimabaixo = false;
                                
                jLabel3.setToolTipText( "Mostrar Submenu" );
                jLabel3.setIcon( icon );  
                
                jp_Padrao_Tabela.setVisible(false);
            }
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "tabJanelaSubmenu, \n"
                + e.getMessage() + "\n", "Alterar_Seta_Submenu" ); }       
    } 
    
    private void JPOpcao_13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_13MouseEntered

    private void JPOpcao_13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_13MouseExited

    private void JPOpcao_13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_13MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_13MousePressed

    private void JPOpcao_12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_12MouseEntered

    private void JPOpcao_12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_12MouseExited

    private void JPOpcao_12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_12MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_12MousePressed

    private void JPOpcao_14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_14MouseEntered

    private void JPOpcao_14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_14MouseExited

    private void JPOpcao_14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_14MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_14MousePressed

    private void JPOpcao_15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_15MouseEntered

    private void JPOpcao_15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_15MouseExited

    private void JPOpcao_15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_15MousePressed

    private void JPOpcao_16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_16MouseEntered

    private void JPOpcao_16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_16MouseExited

    private void JPOpcao_16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_16MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_16MousePressed

    private void JPOpcao_17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_17MouseEntered

    private void JPOpcao_17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_17MouseExited

    private void JPOpcao_17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_17MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_17MousePressed

    private void JPOpcao_18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_18MouseEntered

    private void JPOpcao_18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_18MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_18MouseExited

    private void JPOpcao_18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_18MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_18MousePressed

    private void JPOpcao_19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_19MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_19MouseEntered

    private void JPOpcao_19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_19MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_19MouseExited

    private void JPOpcao_19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_19MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_19MousePressed

    Exportando Exportando;
    private void btSalvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalvarMousePressed
    new Thread() {   @Override public void run() { try { 
        
        if(status_cadastro.equalsIgnoreCase("Cadastrando...")){
            
/* ////// */ControleDeAcesso_Recebido = new ControleDeAcesso();
      
            Exportando = new Exportando("CADASTRANDO");
            Exportando.setVisible(true);
            Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            
            Exportando.pbg.setValue( 50 ); 
            
            verificando_se_o_usuario_e_o_Cleilson();  
            
            Exportando.fechar();             
        }
        else{
      
            Exportando = new Exportando("ALTERANDO");
            Exportando.setVisible(true);
            Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            
            Exportando.pbg.setValue( 50 ); 
            
            verificando_se_o_usuario_e_o_Cleilson();  
            
            Exportando.fechar();  
        }     
            
    }catch( Exception e ){ Exportando.fechar(); e.printStackTrace(); }  } }.start(); 
    }//GEN-LAST:event_btSalvarMousePressed

    private void btExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMousePressed
        try { 
    
            Object[] options = {
                "Confirmar",
                "Cancelar" 
            };
            int n = JOptionPane.showOptionDialog(null,
                    "Confirme a Opção de Excluir o Usuário\n"
                    + "Listado Abaixo.",
                    "Opção de Consulta",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]);
//////////////////////////////////////////////////////
            if(n==0){
        
                //excluir_Usuario_Atual();
            }            
        } catch( Exception e ){} 
    }//GEN-LAST:event_btExcluirMousePressed

    private void JPOpcao_28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_28MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_28MouseEntered

    private void JPOpcao_28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_28MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_28MouseExited

    private void JPOpcao_28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_28MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_28MousePressed

    private void tf_USUARIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_USUARIOMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_USUARIOMouseClicked

    private void tf_USUARIOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_USUARIOMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_USUARIOMouseEntered

    private void tf_USUARIOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_USUARIOMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_USUARIOMouseExited

    private void tf_USUARIOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_USUARIOKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_USUARIOKeyReleased

    private void JPOpcao_29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_29MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_29MouseEntered

    private void JPOpcao_29MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_29MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_29MouseExited

    private void JPOpcao_29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_29MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_29MousePressed

    private void JPOpcao_30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_30MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_30MouseEntered

    private void JPOpcao_30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_30MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_30MouseExited

    private void JPOpcao_30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_30MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_30MousePressed

    private void JPOpcao_34MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_34MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_34MousePressed

    private void JPOpcao_34MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_34MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_34MouseExited

    private void JPOpcao_34MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_34MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_34MouseEntered

    private void cb_TABELAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TABELAActionPerformed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            String string_temp = "";
            try{ 
                string_temp = cb_TABELA.getSelectedItem().toString().trim(); 
            } catch( Exception e ){}

        } catch( Exception e ){  } } }.start();
    }//GEN-LAST:event_cb_TABELAActionPerformed

    UsuarioSistema UsuarioSistemaQueVaiAcessar = null;
    private void jLabel83MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel83MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel83MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPOpcao_12;
    private javax.swing.JPanel JPOpcao_13;
    private javax.swing.JPanel JPOpcao_14;
    private javax.swing.JPanel JPOpcao_15;
    private javax.swing.JPanel JPOpcao_16;
    private javax.swing.JPanel JPOpcao_17;
    private javax.swing.JPanel JPOpcao_18;
    private javax.swing.JPanel JPOpcao_19;
    private javax.swing.JPanel JPOpcao_28;
    private javax.swing.JPanel JPOpcao_29;
    private javax.swing.JPanel JPOpcao_30;
    private javax.swing.JPanel JPOpcao_34;
    private javax.swing.JPanel Pergunta;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    public javax.swing.JComboBox cb_TABELA;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel jpO;
    private javax.swing.JPanel jp_Padrao_Tabela;
    private javax.swing.JLabel lb_Alterado_Por;
    private javax.swing.JLabel lb_Cadastrado_Por;
    private javax.swing.JLabel lb_Data_Cadastro;
    private javax.swing.JLabel lb_Data_Ultima_Alteracao;
    private javax.swing.JRadioButton rb_ACESSO_A_TABELA;
    private javax.swing.JRadioButton rb_ALTERAR;
    private javax.swing.JRadioButton rb_CADASTRAR;
    private javax.swing.JRadioButton rb_CADASTRO_AUTO;
    private javax.swing.JRadioButton rb_CONSULTAR;
    private javax.swing.JRadioButton rb_CONSULTA_SQL;
    private javax.swing.JRadioButton rb_EXCLUIR;
    private javax.swing.JRadioButton rb_VISUALIZAR;
    public javax.swing.JTextField tf_USUARIO;
    // End of variables declaration//GEN-END:variables
    
    public UsuarioSistema get_UsuarioSistema( int id ){ 
        UsuarioSistema retorno = null;
        
        List<UsuarioSistema> UsuarioSistema = null;
        try{ 
            Query q = JPAUtil.em().createNativeQuery("SELECT * FROM JM.USUARIO_SISTEMA WHERE ID = ?", UsuarioSistema.class );
            q.setParameter(1, id );
            List<UsuarioSistema> lista_Banco = q.getResultList();   
            UsuarioSistema = lista_Banco;
        }catch( Exception e ){ }
        
        String rbusca = ""; 
        try{ rbusca = UsuarioSistema.get(0).getLogin(); }catch( Exception e ){}
            
        if( !rbusca.equals("") ){
            
            retorno = UsuarioSistema.get(0);
        }

        return retorno;
    }
    
    private void setar_Visualizacao_Recebida(){                                          
        new Thread(){   @Override public void run() { try{ 
            
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////          
            try{ lb_Cadastrado_Por.setText(get_UsuarioSistema(ControleDeAcesso_Recebido.getIdUsuarioSistemaCadastroControleDeAcesso()  ).getLogin() ); }catch(Exception e){} 
            try{ lb_Alterado_Por.setText(get_UsuarioSistema(ControleDeAcesso_Recebido.getIdUsuarioSistemaAlteracaoControleDeAcesso() ).getLogin() ); }catch(Exception e){}
            
            try{ 
                
                ////////dd.MM.yyyy HH:mm:ss/////////////EEEE, d MMMM yyyy HH:mm:ss
                DateFormat dfmt = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
                String dataCadastro = ""; 
                try{ dataCadastro = dfmt.format(ControleDeAcesso_Recebido.getDataCadastro() ); }catch(Exception e){}
                try{ System.out.println("getDataCadastro - " + ControleDeAcesso_Recebido.getDataCadastro() ); }catch(Exception e){}
                lb_Data_Cadastro.setText( dataCadastro ); 
            }catch(Exception e){} 
            
            try{ 
                
                ////////dd.MM.yyyy HH:mm:ss/////////////EEEE, d MMMM yyyy HH:mm:ss
                DateFormat dfmt = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
                String data_Ultima_Alteracao = ""; 
                try{ data_Ultima_Alteracao = dfmt.format(ControleDeAcesso_Recebido.getDataAlteracao()); }catch(Exception e){}
                try{ System.out.println("getDataAlteracao - " + ControleDeAcesso_Recebido.getDataAlteracao() ); }catch(Exception e){}
                lb_Data_Ultima_Alteracao.setText( data_Ultima_Alteracao ); 
            }catch(Exception e){} 
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////            

            try{ 
                for (int i = 0; i < cb_TABELA.getItemCount(); i++){
                    
                    String string_temp = "";
                    try{ 
                        string_temp = cb_TABELA.getSelectedItem().toString().trim(); 
                    } catch( Exception e ){}
                    
                    if( string_temp.equals(
                        ControleDeAcesso_Recebido.getNomeDaTabela()) ){ 
                        
                        cb_TABELA.setSelectedIndex(i);
                    }
                }
            }catch(Exception e){}

            try{ 
                UsuarioSistema UsuarioSistemaTemp = get_UsuarioSistema( ControleDeAcesso_Recebido.getIdUsuarioSistemaQueVaiAcessar() );
                tf_USUARIO.setText( UsuarioSistemaTemp.getLogin() ); 
            }catch(Exception e){}                      
                        
            try{ rb_ACESSO_A_TABELA.setSelected(
                    ControleDeAcesso_Recebido.getAcessoATabela());
            }catch(Exception e){}
            
            try{ rb_VISUALIZAR.setSelected(
                    ControleDeAcesso_Recebido.getVisualizar());
            }catch(Exception e){}
            
            try{ rb_CONSULTAR.setSelected(
                    ControleDeAcesso_Recebido.getConsultar());
            }catch(Exception e){}
            
            try{ rb_ALTERAR.setSelected(
                    ControleDeAcesso_Recebido.getAlterar());
            }catch(Exception e){}
            
            try{ rb_EXCLUIR.setSelected(
                    ControleDeAcesso_Recebido.getExcluir());
            }catch(Exception e){}
            
            try{ rb_CONSULTA_SQL.setSelected(
                    ControleDeAcesso_Recebido.getConsultaSql());
            }catch(Exception e){}
            
            try{ rb_CADASTRAR.setSelected(
                    ControleDeAcesso_Recebido.getCadastrar());
            }catch(Exception e){}
            
            try{ rb_CADASTRO_AUTO.setSelected(
                    ControleDeAcesso_Recebido.getCadastroAuto());
            }catch(Exception e){}
            
        } catch( Exception e ){  } } }.start();        
    }
    
    private void desabilitar_componentes() {                                          
        new Thread() {   @Override public void run() { try {

            try{ 
                
                cb_TABELA.setEditable(false);
                tf_USUARIO.setEditable(false);
                
                rb_ACESSO_A_TABELA.setEnabled(false);
                rb_VISUALIZAR.setEnabled(false);
                rb_CONSULTAR.setEnabled(false);
                rb_ALTERAR.setEnabled(false);
                
                rb_EXCLUIR.setEnabled(false);
                rb_CONSULTA_SQL.setEnabled(false);
                rb_CADASTRAR.setEnabled(false);
                rb_CADASTRO_AUTO.setEnabled(false);
                
            }catch(Exception e){}
          
        } catch( Exception e ){  } } }.start();        
    }
    
/// CADASTRANDO ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    private void verificando_se_o_usuario_e_o_Cleilson(){ 
        
        try{
            
            if(status_cadastro.equalsIgnoreCase("Cadastrando...")){
                
                verificar_Usuario_Logado();
            }
            else{
                /*
                if( UsuarioSistema_Recebido.getLogin().equalsIgnoreCase("cleilson") ){
                
                    Class<Imagens_Internas> clazzHome = Imagens_Internas.class;
                    JOPM JOptionPaneMod = new JOPM( 1, "ALTERANDO USUÁRIO SELECIONADO\n"
                            + "\nUSUÁRIO: " + UsuarioSistema_Recebido.getLogin() 
                            + "\nVOCÊ NÃO TEM AUTORIZAÇÃO PARA ALTERAR O USUÁRIO CLEILSON"
                            + "\nOK Para Prosseguir"
                            ,"Class: " + this.getClass().getName(),
                            new ImageIcon( clazzHome.getResource("logocangaco2.png")) );  
                }
                else{
                */    
                               
                    verificar_Usuario_Logado();
                //}
            }
            
        }catch( Exception e ){}
    }
            
    private void verificar_Usuario_Logado(){   
        
        String rbusca = ""; 
        try{ rbusca = Login.Usuario_Logado.getLogin(); }catch( Exception e ){}
        
        try{
            
            if( !rbusca.equals("") ){
                
                System.out.println( Login.Usuario_Logado.getLogin() );
                
                verificar_Se_Cadastra_Ou_Altera();
            }
            else{

                Class<br.com.jmary.home.imagens.Imagens_Internas> clazzHome = br.com.jmary.home.imagens.Imagens_Internas.class;
                JOPM JOptionPaneMod = new JOPM( 1, "STATUS DO CADASTRO\n"
                        + "\n"
                        + "\nNÃO HÁ USUÁRIO LOGADO!\n"
                        + "\n"
                        + "\nPARA CADASTRAR É NECESSÁRIO LOGAR!\n"
                        + "\n"
                        + "\nOK PARA PROSSEGUIR"
                        ,"Class: " + this.getClass().getName(), 
                        new ImageIcon( clazzHome.getResource("logocangaco2.png")) );
            }
            
        }catch( Exception e ){ 
            
                e.printStackTrace();
                            
                Class<Imagens_Internas> clazzHome = Imagens_Internas.class;
                JOPM JOptionPaneMod = new JOPM( 1, "USUÁRIO LOGADO\n"
                        + "\n"
                        + "\nUSUÁRIO LOGADO INVÁLIDO!\n"
                        + "\n"
                        + "\nPARA CADASTRAR É NECESSÁRIO LOGAR!\n"
                        + "\n"
                        + "\nOK PARA PROSSEGUIR"
                        ,"Class: " + this.getClass().getName(), 
                        new ImageIcon( clazzHome.getResource("logocangaco2.png")) );
        }
    }
   
    private void verificar_Se_Cadastra_Ou_Altera(){   
        
        List<ControleDeAcesso> ControleDeAcesso = null;
        try{ 
            Query q = JPAUtil.em().createNativeQuery("SELECT * FROM JM.CONTROLEDEACESSO WHERE ID = ?", ControleDeAcesso.class );
            q.setParameter(1, ControleDeAcesso_Recebido.getId() );
            List<ControleDeAcesso> lista_Banco = q.getResultList();   
            ControleDeAcesso = lista_Banco;
        }catch( Exception e ){ }
        
        String rbusca = ""; 
        try{ rbusca = ControleDeAcesso.get(0).getNomeDaTabela(); }catch( Exception e ){}
            
        //É ALTERAÇÃO 
        if( !rbusca.equals("") ){
                
            //CADASTRO / ALTERAÇÃO - USUÁRIO         
            //try{ ControleDeAcesso_Recebido.setIdUsuarioSistemaAlteracaoEstabelecimento( Login.Usuario_Logado.getId() ); }catch( Exception e ){}   
            try{ ControleDeAcesso_Recebido.setIdUsuarioSistemaAlteracaoControleDeAcesso( Login.Usuario_Logado.getId() ); }catch( Exception e ){}   
             
            //CADASTRO / ALTERAÇÃO - DATA - ALTERAÇÃO 
            try{ 
                
                ////////dd.MM.yyyy HH:mm:ss/////////////EEEE, d MMMM yyyy HH:mm:ss
                Calendar calendar = Calendar.getInstance();
                java.util.Date now = calendar.getTime();
                java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(now.getTime());                
                
                DateFormat dfmt = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
                String dataCadastro = ""; 
                try{ dataCadastro = dfmt.format(currentTimestamp);  }catch(Exception e){}
                ////////dd.MM.yyyy HH:mm:ss/////////////EEEE, d MMMM yyyy HH:mm:ss
                
                try{
                    
                    ControleDeAcesso_Recebido.setDataAlteracao( currentTimestamp ); 
                    //UsuarioSistema_Recebido.setDataUltimaAlteracaoSenha( data );
                    
                }catch(Exception e){}
            }catch(Exception e){}

            System.out.println( "Alterando Usuário: " );
                
            setando_os_que_nao_precisam_de_validacao();
        }
        else{
            
            // É CADASTRO 

            //CADASTRO / ALTERAÇÃO - USUÁRIO 
            try{ ControleDeAcesso_Recebido.setIdUsuarioSistemaCadastroControleDeAcesso(Login.Usuario_Logado.getId() ); }catch( Exception e ){}                
            try{ ControleDeAcesso_Recebido.setIdUsuarioSistemaAlteracaoControleDeAcesso(Login.Usuario_Logado.getId() ); }catch( Exception e ){}
                
            //CADASTRO / ALTERAÇÃO - DATA - CADASTRANDO 
            try{ 
                
                ////////dd.MM.yyyy HH:mm:ss/////////////EEEE, d MMMM yyyy HH:mm:ss
                Calendar calendar = Calendar.getInstance();
                java.util.Date now = calendar.getTime();
                java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(now.getTime());                
                
                DateFormat dfmt = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
                String dataCadastro = ""; 
                try{ dataCadastro = dfmt.format(currentTimestamp);  }catch(Exception e){}
                ////////dd.MM.yyyy HH:mm:ss/////////////EEEE, d MMMM yyyy HH:mm:ss
                
                try{

                    ControleDeAcesso_Recebido.setDataCadastro( currentTimestamp ); 
                    
                    ControleDeAcesso_Recebido.setDataAlteracao( currentTimestamp ); 
                    
                }catch(Exception e){}
            }catch(Exception e){} 

            System.out.println(  "Novo Usuário: " );
                
            setando_os_que_nao_precisam_de_validacao();
        }
    }
    
    private void setando_os_que_nao_precisam_de_validacao(){ 
        
        try{
            
            try{ 
                
                String string_temp = "";
                try{ 
                    string_temp = cb_TABELA.getSelectedItem().toString().trim(); 
                } catch( Exception e ){}
                
                ControleDeAcesso_Recebido.setNomeDaTabela(string_temp);                        
            }catch(Exception e){}                                 
                        
            try{ ControleDeAcesso_Recebido.setAcessoATabela(
                     rb_ACESSO_A_TABELA.isSelected() );
            }catch(Exception e){}
            
            try{ ControleDeAcesso_Recebido.setVisualizar(
                    rb_VISUALIZAR.isSelected() );
            }catch(Exception e){}
            
            try{ ControleDeAcesso_Recebido.setConsultar(
                    rb_CONSULTAR.isSelected() );
            }catch(Exception e){}
            
            try{ ControleDeAcesso_Recebido.setAlterar(
                    rb_ALTERAR.isSelected());
            }catch(Exception e){}
            
            try{ ControleDeAcesso_Recebido.setExcluir(
                    rb_EXCLUIR.isSelected());
            }catch(Exception e){}
            
            try{ ControleDeAcesso_Recebido.setConsultaSql(
                    rb_CONSULTA_SQL.isSelected());
            }catch(Exception e){}
            
            try{ ControleDeAcesso_Recebido.setCadastrar(
                    rb_CADASTRAR.isSelected());
            }catch(Exception e){}
            
            try{ ControleDeAcesso_Recebido.setCadastroAuto(
                    rb_CADASTRO_AUTO.isSelected());
            }catch(Exception e){}
            
            verificar_UsuarioSistemaQueVaiAcessar();
            
        }catch( Exception e ){}
    }
    
    private void verificar_UsuarioSistemaQueVaiAcessar(){ 
        
        try{ 
            
            List<UsuarioSistema> UsuarioSistema = null;
            try{ 
                Query q = JPAUtil.em().createNativeQuery("SELECT * FROM JM.USUARIO_SISTEMA WHERE ID = ?", UsuarioSistema.class );
                q.setParameter(1, UsuarioSistemaQueVaiAcessar.getId() );
                List<UsuarioSistema> lista_Banco = q.getResultList();   
                UsuarioSistema = lista_Banco;
            }catch( Exception e ){ }
        
            String rbusca = ""; 
            try{ rbusca = UsuarioSistema.get(0).getLogin(); }catch( Exception e ){}
            
            if( !rbusca.equals("") ){
            
                ControleDeAcesso_Recebido.setIdUsuarioSistemaQueVaiAcessar( UsuarioSistema.get(0).getId() );
            
                cadastrar();
            }
            else{
                
                Class<Imagens_Internas> clazzHome = Imagens_Internas.class;
                JOPM JOptionPaneMod = new JOPM( 1, "CAMPO USUÁRIO\n"
                    + "\n"
                    + "\nO CAMPO USUÁRIO ESTÁ VAZIO!\n"
                    + "\n"
                    + "\nPARA CADASTRAR É NECESSÁRIO INFORMAR UM USUÁRIO!\n"
                    + "\n"
                    + "\nOK PARA PROSSEGUIR"
                    ,"Class: " + this.getClass().getName(), 
                    new ImageIcon( clazzHome.getResource("logocangaco2.png")) );
            }
            
            
        }catch(Exception e){}
    }
    
    private void cadastrar(){  
        try{
            /*
            try{ System.out.println( "\n-----------------------------------------------" ); }catch( Exception e ){}
            try{ System.out.println(ControleDeAcesso_Recebido.getPessoaFisica() ); }catch( Exception e ){}
            try{ System.out.println(ControleDeAcesso_Recebido.getPessoaJuridica()); }catch( Exception e ){}
            try{ System.out.println(ControleDeAcesso_Recebido.getNomeOuRazaoSocial()); }catch( Exception e ){}
            try{ System.out.println(ControleDeAcesso_Recebido.getCodigoDeIdentificacao()); }catch( Exception e ){}
            try{ System.out.println(ControleDeAcesso_Recebido.getNomeOuFantasia()); }catch( Exception e ){}
            try{ System.out.println(ControleDeAcesso_Recebido.getCpfOuCnpj()); }catch( Exception e ){}
            try{ System.out.println(ControleDeAcesso_Recebido.getDataCadastro()); }catch( Exception e ){}
            try{ System.out.println(ControleDeAcesso_Recebido.getIdUsuarioSistemaCadastroEstabelecimento()); }catch( Exception e ){}
            try{ System.out.println(ControleDeAcesso_Recebido.getDataAlteracao()); }catch( Exception e ){}
            try{ System.out.println(ControleDeAcesso_Recebido.getIdUsuarioSistemaAlteracaoEstabelecimento()); }catch( Exception e ){}
            try{ System.out.println( "-----------------------------------------------\n" ); }catch( Exception e ){}
            */
                    
            DAOGenericoJPA DAOGenericoJPA2 = new DAOGenericoJPA( ControleDeAcesso_Recebido, JPAUtil.em());
            ControleDeAcesso ControleDeAcesso_Cadastrado = (ControleDeAcesso) DAOGenericoJPA2.gravanovoOUatualizar();

            ///////////////////////////////////////////////////
            if(status_cadastro.equalsIgnoreCase("Cadastrando...")){                
                ControleDeAcesso_Recebido = ControleDeAcesso_Cadastrado;
                status_cadastro = "Visualizando...";
                setar_Dados_Iniciais();  
            }
            ///////////////////////////////////////////////////
            
            String rbusca = ""; 
            try{ rbusca = ControleDeAcesso_Recebido.getNomeDaTabela().toUpperCase(); }catch( Exception e ){}
        
            Class<Imagens_Internas> clazzHome = Imagens_Internas.class;
            JOPM JOptionPaneMod = new JOPM( 1, "CADASTRO\n"
                    + "\n"
                    + "\nSTATUS DO CADASTRO\n"
                    + "\n"
                    + "\nCONTROLE_DE_ACESSO "+ rbusca 
                    + "\nCADASTRADO COM SUCESSO!\n"
                    + "\n"
                    + "\nOK PARA PROSSEGUIR"
                    ,"Class: " + this.getClass().getName(), 
                    new ImageIcon( clazzHome.getResource("logocangaco2.png")) );
        }catch( Exception e ){
            
            System.out.println("Erro ao cadastrar");
            e.printStackTrace();
        }
    }
/// CADASTRANDO ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
       
}